# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-12 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('link', models.URLField(help_text='The URL to the image page', max_length=255, verbose_name='Photo Link')),
                ('image_url', models.URLField(help_text='The URL to the image file itself', max_length=255, verbose_name='Image URL')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Photos',
                'verbose_name': 'Photo',
                'ordering': ['-created_on', 'title'],
            },
        ),
    ]
